### PR TITLE
initial proposal for the additional RDF schema used by openwordnet-PT

### PR DESCRIPTION
**Pull request by arademaker**
this PR contains preliminary documentation about another RDF vocabulary for encoding wordnets.  In the absence of a better name, I am using `wn simple`. Further details comparing it to the Lemon-based vocabulary and generalizations from the original version at http://github.com/own-pt/openWordnet-PT will be provided in the near future.

### CODE REVIEW

**Comment by arademaker** [comment]
@jmccrae the `index.md` file was not updated? My changes are in the table of contents and in the first paragraph of the RDF section. My idea was just to generalize the description of RDF encoding showing that we have at least, two possible vocabularies.

**Comment by jmccrae** [comment]
It seems the change to the ToC got overwritten in another PR. The changes in the text are available in the `release-1.1` branch

**Comment by arademaker** [comment]
Hi @jmccrae , can you please point me to what branch I should work to recover my previous suggestions? Currently, in https://globalwordnet.github.io/schemas/  we are still ignoring the fact that Lemon-RDF isn't the only way to encode wordnets in RDF.

**Comment by jmccrae** [comment]
@arademaker the changes you made are on this branch https://github.com/globalwordnet/schemas/commits/wn-simple

As far as I can see, they are in `release-1.1` and nothing else was ever pushed to GitHub.

**Pull request merged**
