### PR TITLE
Release 1.1

### PR DESCRIPTION
**Pull request by jmccrae**
This the pull request for the 1.1 Release Candidate of the GWA Schemas. Let me know if I have missed anything

### CODE REVIEW

**Comment by fcbond** [comment]
Hi,

I still need to add the new relations.   I will try to do that today.

**Comment by goodmami** [comment]
Weren't we going to change the URL of the `dc` namespace? (see https://github.com/globalwordnet/schemas/issues/24#issuecomment-670516816)

**Comment by goodmami** [comment]
> Weren't we going to change the URL of the `dc` namespace? (see [#24 (comment)](https://github.com/globalwordnet/schemas/issues/24#issuecomment-670516816))

For this, see #39.

**Comment by goodmami** [comment]
If it's not too late, why is the `id` attribute of the new `<SyntacticBehaviour>` elements `#IMPLIED`? Without it, the senses have nothing to refer to in their `subcat` attribute, and the syntactic behaviour entity would be useless. Can't this be `#REQUIRED`?

**Comment by jmccrae** [comment]
The `id` attribute is not required so that we have backwards compatibility with the previous schema.

**Comment by goodmami** [comment]
Ah yes, compatibility. So is the intention (that cannot be spelled out in DTD) then that the attribute *should* be required when the element appears under `<Lexicon>` and forbidden when the element appears under `<LexicalEntry>`? That is, when we eventually shed ourselves of the constraint of compatibility, it will become required? In any case, I guess for now I cannot rely on the presence of the `id` attribute.

**Comment by jmccrae** [comment]
Yes, it can't really be enforced by the DTD. I would also note that a syntactic behaviour underneath the lexicon with no ID is obviously useless, so it should be clear to data providers that an ID is needed and data consumers could just discard this.

**Pull request merged**
