### PR TITLE
Release 1.2

### PR DESCRIPTION
**Pull request by jmccrae**
Branch for tracking changes that will go into the 1.2 version

### CODE REVIEW

**Comment by simongray** [comment]
Are all of the various schema files edited individually or do you have one or more master files to derive the others from?

If you edit them all individually, is there a way to ensure consistency? E.g. tests or something similar.

**Comment by jmccrae** [comment]
The `.rdf` files are converted from `.ttl` files using `rapper`. Everything else is just done very carefully :)

**Comment by simongray** [comment]
Ok. Good to know. So if I just make changes to the `.ttl` files you can take it from there?

**Comment by jmccrae** [comment]
Yes that would be great.

**Comment by simongray** [comment]
Currently need to make a deliverable for a different project where we have a status meeting next week, so I won't be able to take a look at this before the second half of next week.

**Comment by simongray** [comment]
Hey @jmccrae and others. I was wondering whether this version could be made official? I am winding down most of my work in december, so it would be great to be able to have the final schema to point to :-)

**Comment by jmccrae** [comment]
I think we can release

**Pull request merged**
